name: Compile

on:
  pull_request:
    branches: [master]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install "cython>3,<3.2" setuptools

      - name: Build Cython extensions
        run: make cython

      - name: Prepare build directory
        run: |
          rm -rf build
          mkdir build
          cp cchecksum/*.c build/

      - name: Check for changes in build/
        id: check_changes
        run: |
          git add build/
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes (if possible)
        if: steps.check_changes.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: compile C files for source control"
          git push

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true' && github.event_name != 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto/update-cython-cfiles
          base: ${{ github.head_ref || github.ref_name }}
          title: "chore: compile C files for source control"
          body: |
            This PR updates generated C files in /build based on the latest implementation. Generated by GitHub Actions.
            Triggered by #${{ github.event.pull_request.number }}
          commit-message: "chore: compile C files for source control"
          delete-branch: true
